finos/kdb-studio

- src/org/netbeans/editor/EditorUI.java
- src/studio/kdb/Config.java
- src/studio/ui/SettingsDialog.java
- src/studio/ui/StudioPanel.java
> add font configuration

- .github/ISSUE_TEMPLATE/Bug_report.md
- .github/ISSUE_TEMPLATE/Feature_request.md
- .github/ISSUE_TEMPLATE/Support_question.md
This pull request adds three FINOS Issues Templates to the `.github/ISSUE_TEMPLATE` folder of the kdb-studio project to enable **Bug Reporting**, **Feature Requests** and **Support Questions** to be raised by the kdb-studio community.
These Issue templates are accessed via the `New issue` button featured on the kdb-studio issues page : 
https://github.com/finos/kdb-studio/issues
File : `Bug_report.md`
```
---
name: 🐛 Bug Report
about: If something isn't working as expected 🤔.
---
1. ...step 1 description...
2. ...step 2 description...
3. ...step 3 description...
...description of what you expected to see...
...what actually happened, including full exceptions (please include the entire stack trace, including "caused by" entries), log entries, screen shots etc. where appropriate... …
```
> Add FINOS GitHub Issue Templates from FINOS Project Blueprint

- src/studio/kdb/Config.java
- src/studio/ui/SettingsDialog.java
- src/studio/ui/StudioPanel.java
> add option to switch between CR+LF and LF line endings

- src/studio/ui/ExcelExporter.java
> use blank value instead of "???" for nulls

- src/studio/ui/StudioPanel.java
- src/studio/ui/Util.java
> set font on results pane to avoid null pointer exception

- src/studio/kdb/Config.java
- src/studio/ui/ServerForm.java
> allow setting the default auth method via environment variable

- src/studio/kdb/Config.java
> Config - Fix for java 11

- src/studio/kdb/Config.java
- src/studio/ui/ServerList.java
- src/studio/ui/SettingsDialog.java
- src/studio/ui/StudioPanel.java
Integrate PR from dzmipt push to CharlesSkelton/studio + add context menu to close tabs
THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS “AS IS” AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND ANY WARRANTY OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY …
> Add tab to output

- src/studio/ui/StudioPanel.java
> StudioPanel - Close current tab with middle click

- .github/workflows/main.yml
- build.gradle
- src/studio/core/Studio.java
- src/studio/kdb/Config.java
- src/studio/ui/StudioPanel.java
- src/test/StudioTest.java
- test.sh
> add GUI test

- src/kx/c.java
> fix: mapped table objects cause exception

- src/kx/c.java
- src/org/netbeans/editor/example/Editor.java
- src/org/netbeans/editor/example/res/StudioEditor.java
- src/studio/ui/ExcelExporter.java
- src/studio/ui/ExceptionGroup.java
- src/studio/ui/QGrid.java
- src/studio/ui/ServerForm.java
- src/studio/ui/ServerList.java
- src/studio/ui/StudioOptionPane.java
- src/studio/ui/StudioPanel.java
- src/studio/utils/BrowserLaunch.java
> allow message dialog mnemonics to be used without the alt key

- .github/workflows/main-java11.yml
- build.gradle
> add build for java 11

- src/main/studio/kdb/K.java
- src/test/studio/kdb/KTest.java
> K - Fix toString for vector and primitive

- src/main/studio/kdb/Config.java
- src/main/studio/ui/SettingsDialog.java
- src/main/studio/ui/StudioPanel.java
> Add option to turn console view on/off

- readme.md
Enable inbound inquiries to reach maintainers directly
> Updating readme.md to reference maintainers list

- src/main/studio/ui/StudioPanel.java
> StudioPanel - show console view if no "table" output

- src/main/studio/ui/StudioPanel.java
> Syntax highliting in console view

- gradle/wrapper/gradle-wrapper.properties
> gradle-wrapper.properties - upgrade to 6.8.3

- src/main/studio/kdb/K.java
- src/main/studio/ui/QGrid.java
> QGrid - Fix post merge

- src/main/kx/c.java
> don't show backtick before error messages

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
> migrate to gradle 7

- src/main/org/netbeans/editor/SettingsDefaults.java
- src/main/studio/ui/StudioPanel.java
> Clean up warnings

- src/main/studio/ui/StudioPanel.java
> force locale to en-US, to prevent usage of commas for decimal separators

- src/test/studio/kdb/KTest.java
> set locale to EN-US even in tests

- src/main/studio/ui/StudioPanel.java
> allow the user to pass in host:port on the command line

- src/main/studio/kdb/K.java
- src/main/studio/ui/action/CopyTableSelectionAction.java
This is merging the change from this PR: #46
> QGrid - Improve date format when exporting to Excel

- .github/workflows/main-java11.yml
- .github/workflows/main-java17.yml
- .github/workflows/main.yml
- build.gradle
- src/main/studio/core/Studio.java
- src/main/studio/ui/StudioPanel.java
- src/main/studio/ui/rstextarea/StudioRSyntaxTextArea.java
- src/test-integration/studio/StudioTest.java
- test.sh
> fix integration test after importing changes

- build.gradle
- src/test-integration/studio/StudioTest.java
- src/test-integration/studio/kdb/KSerialiseTest.java
> Move KSerialiseTest to integration test

- notes.md
- src/main/studio/core/Studio.java
- src/main/studio/ui/StudioPanel.java
- src/main/studio/ui/Util.java
- src/main/studio/utils/OSXAdapter.java
> Pull more changes from Dmitry

- src/main/studio/kdb/K.java
- src/test/studio/kdb/KTest.java
> Finos fixing k formating

- .github/workflows/main-java11.yml
- .github/workflows/main-java17.yml
- .github/workflows/main.yml
- src/main/studio/kdb/Config.java
- src/main/studio/ui/SettingsDialog.java
- src/main/studio/ui/StudioPanel.java
- src/main/studio/ui/rstextarea/RSTextAreaFactory.java
> add settings to change the tab size and usage of tab vs space characters

- src/main/studio/ui/chart/Chart.java
- src/main/studio/ui/chart/ChartConfigPanel.java
- src/main/studio/ui/chart/ChartType.java
- src/main/studio/ui/chart/SquareIcon.java
> Chart - add check box to show legend on chart

- src/main/studio/ui/SearchPanel.java
> Select find text (issue #91) and Fix Find Back (issue #93)

- src/main/studio/ui/EditorPane.java
- src/main/studio/ui/SearchPanel.java
- src/main/studio/ui/rstextarea/FindNextAction.java
- src/main/studio/ui/rstextarea/RSTextAreaFactory.java
> add shortcuts F3/Shift+F3 to find next and previous

- src/main/studio/ui/EditorPane.java
- src/main/studio/ui/EditorTab.java
- src/main/studio/ui/SearchPanel.java
> improve message when search wraps around, flash alerts in red on status bar

- src/main/studio/ui/SearchPanel.java
- src/test-integration/studio/StudioTest.java
> fix replace button replacing the wrong occurrence on the 2nd press

- src/main/studio/ui/StudioPanel.java
Fixes #117 
* recent files are opened on new tabs, consistent with opening them via the Open menu option
* existence of file is checked before opening, to avoid opening a broken tab
* if a file is already open, its tab is activated instead of opening a new tab
THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS “AS IS” AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND ANY WARRANTY OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL …
> improvements to opening files

- src/main/studio/core/Studio.java
- src/main/studio/kdb/Config.java
- src/main/studio/ui/SettingsDialog.java
- src/main/studio/ui/StudioPanel.java
> add option to disable file watcher

- src/main/studio/ui/StudioPanel.java
Fixes #102 and #100.
THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS “AS IS” AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND ANY WARRANTY OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT …
> improve UX related to search box focus

- src/main/studio/ui/chart/Chart.java
> allow chart windows to be closed with Ctrl+W

- src/main/studio/ui/EditorPane.java
- src/main/studio/ui/TabPanel.java
> enable line wrapping in output console

- src/main/studio/ui/SearchPanel.java
- src/main/studio/utils/OrderFocusTraversalPolicy.java
- src/test-integration/studio/StudioTest.java
> history for search and replace text

- src/main/studio/core/Studio.java
- src/main/studio/kdb/Config.java
- src/main/studio/qeditor/RSTokenMaker.java
- src/main/studio/ui/SettingsDialog.java
- src/main/studio/ui/StudioPanel.java
> disable auto-unidenting of closing curly braces

- readme.md
> cleanup the readme

- src/main/studio/ui/StudioPanel.java
> in the open file dialog, browse from the file in the current tab

- build.gradle
- src/main/studio/ui/StudioPanel.java
> fix null pointer exception when opening files

- build.gradle
> restore application/mainClass attribute

- src/main/studio/ui/TabPanel.java
> make error display respect the font size setting
